import Head from "next/head";
import Link from "next/link";
import { type PropsWithChildren } from "react";

interface Props {
  page: string;
}

const Layout: React.FC<PropsWithChildren<Props>> = ({ children, page }) => {
  return (
    <>
      <Head>
        <title>Progress Tracker 2 | {page}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Link className="m-1" href="/">
          Home
        </Link>
        <Link className="m-1" href="/profile">
          Profile
        </Link>
      </nav>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-400">
        {children}
      </main>
    </>
  );
};

export default Layout;
