import Head from "next/head";
import { type PropsWithChildren } from "react";

const FrontPageLayout: React.FC<PropsWithChildren> = ({ children }) => {
  const title = `Welcome | Progress Journal`;
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full flex-col items-center bg-neutral-800 font-montserrat">
        {children}
      </div>
    </>
  );
};

export default FrontPageLayout;
