import { type NextPage } from "next";
import Head from "next/head";

interface Field {
  name: string;
  value: number;
  unit?: string;
}

interface Entry {
  name: string;
  fields: Field[];
}

const Entries: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto flex max-w-full flex-col items-center justify-center">
        <EntryRow
          name="Test prop"
          fields={[
            { name: "lol", value: 12, unit: "kg" },
            { name: "testing", value: 200, unit: "somes" },
            { name: "counter", value: 2}
          ]}
        />
      </main>
    </>
  );
};

export default Entries;

const EntryRow: React.FC<Entry> = (props) => {
  return (
    <div className="flex flex-row justify-evenly">
      <div className="w-36 bg-slate-400 p-4">{props.name}</div>
      {props.fields.map((field, index) => {
        return (
          <div
            className="w-auto bg-slate-400 p-4"
            key={`${field.name}+${field.value}+${index}`}
          >
            {field.name}:<br />
            <strong>{field.value}{field.unit}</strong>
          </div>
        );
      })}
    </div>
  );
};
